### ISSUE TITLE
No idea how to get started

### ISSUE THREAD

**Issue by MS-Jahan** [xeffyr/termux-extra-packages#23]
I have added your repo successfully. But I have no idea what packages I should install in order to get the Desktop working in the VNC Viewer app. Is there any script or just tell me what packages I should install and the command to start the VNC. 

Thanks in Advance... :-)

**Comment by Hax4us** [comment]
Its your choice but for testing you can install openbox `apt install openbox`

**Comment by MS-Jahan** [comment]
I am a newbie here. I have entered vncserver in the terminal opened the VNC viewer app. I haven't found any Taskbar or panel or any icon of gui apps. Do I have to enter commands for each apps in the terminal to get started with gui apps in the VNC viewer?

Sorry for stupid questions...

**Comment by xeffyr** [comment]
> I have entered vncserver in the terminal opened the VNC viewer app. I haven't found any Taskbar or panel or any icon of gui apps.

@MS-Jahan VNC server doesn't provide desktop environment. It only needed for graphical output over VNC. It is possible to use [Xorg XSDL](https://play.google.com/store/apps/details?id=x.org.server) (standalone XServer server for Android) instead of `tigervnc`.

There is no complete desktop environment in this repository and likely never be. Only window managers like **i3**, **openbox**, **fluxbox**. Since these packages are common, all information about how to configure them available in the Internet.

> Do I have to enter commands for each apps in the terminal to get started with gui apps in the VNC viewer?

At least these commands if you have tigervnc and fluxbox installed:
```
vncserver
export DISPLAY=:1
fluxbox &
```
However `DISPLAY` variable may be different if you forget to stop `vncserver` before exiting Termux (usually, you should do `vncserver -kill :1` after finishing).

**Comment by MS-Jahan** [comment]
That's a lot of help. Thank you so much! :-)
