### ISSUE TITLE
Key 9D6D488416B493F0 can't be found

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [xeffyr/termux-extra-packages#28]
I've been trying to install this to my Termux instance, but the key retrieving only failed with key server errors.
I've searched the key on http://pool.sks-keyservers.net (web browser), but even there it's impossible to find the key.

**Comment by xeffyr** [comment]
> there it's impossible to find the key.

![2018-08-02 12-17-55](https://user-images.githubusercontent.com/25881154/43575013-55bf1a0c-964e-11e8-8a8d-5a4a3fb4751c.png)

^ *You need to search better*.

![screenshot_20180802-121242_termux](https://user-images.githubusercontent.com/25881154/43575239-0353b042-964f-11e8-9459-cc134fd978ab.jpg)

^ Key import is working because *gpg key exists*.

You may need to execute `apt-key adv --keyserver pool.sks-keyservers.net --recv 9D6D488416B493F0` several times before key gets successfully imported (pool returned a bad gpg server ?).

**Comment by kaeptmblaubaer1000** [comment]
@xeffyr your url shows that you prepended `0x` to the search (I didn't) and since I used a buggy internet connection, I had to use `hkp://p80.pool.sks-keyservers.net:80`.

**Comment by Ambroise7** [comment]
m Packages
Err:5 https://hax4us.github.io/termux-tools termux/extras all Packages
  404  Not Found
Ign:6 https://hax4us.github.io/termux-tools termux/extras arm Packages
Reading package lists... Done
E: Failed to fetch https://hax4us.github.io/termux-tools/dists/termux/extras/binary-all/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead


 I see this error When i try to install beef... please how to resolve

**Comment by Hax4us** [comment]
@Ambroise7 
My repo is changed to `deb [trusted=yes] https://hax4us.github.io/termux-tools extras main `

**Comment by Ambroise7** [comment]
So how can I do now

**Comment by Hax4us** [comment]
https://github.com/Hax4us/termux-tools/blob/master/README.md
Follow this

**Comment by Ambroise7** [comment]
Thanks i resolve it

Le jeu. 23 août 2018 17:34, Informa Tutos <informatutos7@gmail.com> a
écrit :

> So how can I do now
>
